/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "twequpsdukdwmrbdnafm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZXF1cHNkdWtkd21yYmRuYWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MzgyODksImV4cCI6MjA3ODMxNDI4OX0.AiW-WVdjhx7YQ4B7HYwVwzQ0yb5z-p2UsH9_npMGRHs"